# Generated by Django 4.2.6 on 2023-10-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'клиент сервиса', 'verbose_name_plural': 'клиенты сервиса'},
        ),
        migrations.CreateModel(
            name='MailingListSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='время начала рассылки')),
                ('end_time', models.TimeField(verbose_name='время окончания рассылки')),
                ('periodicity', models.DurationField(choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], verbose_name='периодичность')),
                ('status', models.CharField(choices=[('completed', 'Завершена'), ('created', 'Создана'), ('started', 'Запущена')], max_length=50, verbose_name='статус рассылки')),
                ('subject', models.CharField(max_length=250, verbose_name='тема письма')),
                ('text', models.TextField(verbose_name='тело письма')),
                ('status_message', models.CharField(choices=[('TO_BE_SENT', 'К отправке'), ('SHIPPED', 'Отправлено')], default='К отправке', max_length=50, verbose_name='статус отправки')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.client', verbose_name='клиенты рассылки')),
            ],
            options={
                'verbose_name': 'настройка рассылки',
                'verbose_name_plural': 'настройки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('status', models.BooleanField(verbose_name='статус попытки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.client', verbose_name='клиент рассылки')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.mailinglistsettings', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
