# Generated by Django 4.2.6 on 2023-10-11 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_client_options_mailinglistsettings_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglistsettings',
            name='periodicity',
            field=models.DurationField(choices=[(datetime.timedelta(days=1), 'Раз в день'), (datetime.timedelta(days=7), 'Раз в неделю'), (datetime.timedelta(days=30, seconds=43200), 'Раз в месяц')], verbose_name='периодичность'),
        ),
    ]
