# Generated by Django 4.2.6 on 2023-10-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_mailinglistsettings_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglistsettings',
            name='clients',
        ),
        migrations.AddField(
            model_name='mailinglistsettings',
            name='clients',
            field=models.ManyToManyField(to='service.client', verbose_name='клиенты рассылки'),
        ),
    ]
