# Generated by Django 4.2.6 on 2023-10-12 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_mailinglistsettings_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='server_response',
        ),
        migrations.AlterField(
            model_name='mailinglistsettings',
            name='periodicity',
            field=models.DurationField(choices=[(datetime.timedelta(days=1), 'Раз в день'), (datetime.timedelta(days=7), 'Раз в неделю'), (datetime.timedelta(days=30, seconds=43200), 'Раз в месяц')], default=datetime.timedelta(days=30, seconds=43200), verbose_name='периодичность'),
        ),
    ]
