# Generated by Django 4.2.5 on 2023-10-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_client_owner_mailinglistsettings_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglistsettings',
            options={'permissions': [('change_status', 'Can turn off mailing')], 'verbose_name': 'настройка рассылки', 'verbose_name_plural': 'настройки рассылки'},
        ),
    ]
